//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_Cliente { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> N_Cuenta { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
