INICIO:
MOV	P1,#33H
AQUI1:  JNB P3.5,AQUI1; APAGAR/PRENDER MOTOR
;///////////////////////////////////////////////////////////////////////////;
programa:        JNB P3.4,AQUI2; //Si P3.4=0  SALTAS AL PROGRAMA 2 (N. vueltas)
OTRA:   JNB P3.3,LEFT; //si P3.3=0   SALTAS A MOVER A LA IZQUIERDA EL MOTOR
;///////////////////////////////////////////////////////////////////////////;
CICLOO:
        JNB P3.2,AQUI4 ;VELOCIDAD 1
CICLO:  LCALL DERVEL1
        JNB P3.5,AQUI1; SE APAGA
        JNB P3.4,AQUI2
        JNB P3.3,LEFT
AQUI4:  JB P3.2,CICLO ;VELOCIDAD 2
CICLO2: LCALL DERVEL2
        JNB P3.5,AQUI1; SE APAGA
        JNB P3.4,AQUI2
        JNB P3.3,LEFT
        JNB P3.2,CICLO2
        JB P3.2,CICLOO
;///////////////////////////////////////////////////////////////////////////;
LEFT:
         JNB P3.2,AQUI5 ;//PRIMERA VEZ QUE SE VERIFICA ¿QUÉ VELOCIDAD QUIERES?
CICLO3:  LCALL IZQVEL1
         JNB P3.5,AQUI1; //VERIFICA SI QUIERES APAGAR MOTOR
         JNB P3.4,AQUI2;  //VERIFICA SI QUIERES IR A PROGRAMA 2
         JB  P3.3,CICLOO ;//VERIFICA SI QUIERES SEGUIR EN LA MISMA DIRECCIÓN
AQUI5:   JB P3.2,CICLO3 ;//VERIFICA QUE QUIERAS SEGUIR EN VELOCIDAD1
CICLO4:  LCALL IZQVEL2
         JNB P3.5,AQUI1;  //VERIFICA SI QUIERES APAGAR EL MOTOR
         JNB P3.4,AQUI2; //VERIFICA SI QUIERES CAMBIARTE AL PROGRAMA 2
         JB  P3.3,CICLOO; //VERIFICA SI QUIERES CAMBIAR DE DIRECCIÓN
         JNB P3.2,CICLO4;  //VERIFICA SI QUIERES SEGUIR EN LA MISMA VELOCIDAD
         JB P3.2,CICLO3;  //SALTA A VELOCIDAD1 
AQUI2:                             ;PARTE 2 DEL PROGRAMA
	MOV A,P3
	ANL A,#03H
	MOV R0,A
	CJNE R0,#00H,VUELTAS
	LJMP FIN
VUELTAS:
repit3:	MOV R2,#5D
repit2:	MOV R1,#100D
repit1:	LCALL DERVEL1
	DJNZ R1,repit1
	DJNZ R2,repit2
	DJNZ R0,repit3
        JNB P3.4,AQUI2
	JB P3.4,programa
	LJMP FIN
FIN:	LJMP	AQUI1; // El programa se queda aquí hasta que le des reset.
VELOCIDAD1:
	MOV	R5, #03D
CETI3:	MOV	R6, #20D
CETI2:	MOV	R7, #20D
CETI1:	DJNZ	R7, CETI1
	DJNZ	R6, CETI2
	DJNZ	R5, CETI3
	RET

VELOCIDAD2:
	MOV	R5, #08D
CETI6:	MOV	R6, #20D
CETI5:	MOV	R7, #20D
CETI4:	DJNZ	R7, CETI4
	DJNZ	R6, CETI5
	DJNZ	R5, CETI6
	RET

IZQVEL1: 
        MOV P1, #01H;
        LCALL VELOCIDAD1
        MOV P1, #02H
        LCALL VELOCIDAD1
	MOV P1, #04H
	LCALL VELOCIDAD1
	MOV P1, #08H
	LCALL VELOCIDAD1
	RET

DERVEL1:     
        MOV P1, #08H
	LCALL VELOCIDAD1
        MOV P1, #04H
	LCALL VELOCIDAD1
	MOV P1, #02H
	LCALL VELOCIDAD1
	MOV P1, #01H
        LCALL VELOCIDAD1
        RET

IZQVEL2: 
        MOV P1, #01H;
        LCALL VELOCIDAD2
        MOV P1, #02H
        LCALL VELOCIDAD2
	MOV P1, #04H
	LCALL VELOCIDAD2
	MOV P1, #08H
	LCALL VELOCIDAD2
	RET

DERVEL2:     
        MOV P1, #08H
	LCALL VELOCIDAD2
        MOV P1, #04H
	LCALL VELOCIDAD2
	MOV P1, #02H
	LCALL VELOCIDAD2
	MOV P1, #01H
        LCALL VELOCIDAD2
        RET
        
RETARDO:
	MOV	R5, #02D
CETI9:	MOV	R6, #100D
CETI8:	MOV	R7, #100D
CETI7:	DJNZ	R7, CETI7
	DJNZ	R6, CETI8
	DJNZ	R5, CETI9
	RET
RET
END