/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar;

/**
 *
 * @author carlo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rmaterias = new javax.swing.JButton();
        Rprofes = new javax.swing.JButton();
        Ralumnos = new javax.swing.JButton();
        Valumnos = new javax.swing.JButton();
        Vmaterias = new javax.swing.JButton();
        Vprofesores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rmaterias.setBackground(new java.awt.Color(255, 255, 255));
        Rmaterias.setText("Registro Materias");
        Rmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmateriasActionPerformed(evt);
            }
        });
        getContentPane().add(Rmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 230, 60));

        Rprofes.setText("Registro Profesores");
        Rprofes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprofesActionPerformed(evt);
            }
        });
        getContentPane().add(Rprofes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 230, 60));

        Ralumnos.setText("Registro Alumnos");
        Ralumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RalumnosActionPerformed(evt);
            }
        });
        getContentPane().add(Ralumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 230, 60));

        Valumnos.setText("Ver Alumnos");
        Valumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValumnosActionPerformed(evt);
            }
        });
        getContentPane().add(Valumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 230, 60));

        Vmaterias.setText("Ver Materias");
        Vmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VmateriasActionPerformed(evt);
            }
        });
        getContentPane().add(Vmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 230, 60));

        Vprofesores.setText("Ver Profesores");
        Vprofesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VprofesoresActionPerformed(evt);
            }
        });
        getContentPane().add(Vprofesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTROL ESCOLAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 480, 40));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SALIR");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizarron.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VprofesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VprofesoresActionPerformed
        VerProfesoresFrame menu = new VerProfesoresFrame();
        menu.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_VprofesoresActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void RprofesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprofesActionPerformed
        RegistroProfesoresFrame menu = new RegistroProfesoresFrame();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RprofesActionPerformed

    private void RalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RalumnosActionPerformed
        RegistroAlumnosFrame menu = new RegistroAlumnosFrame();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RalumnosActionPerformed

    private void RmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmateriasActionPerformed
        RegistroMateriasFrame menu = new RegistroMateriasFrame();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RmateriasActionPerformed

    private void ValumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValumnosActionPerformed
        VerAlumnosFrame menu = new VerAlumnosFrame();
        menu.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_ValumnosActionPerformed

    private void VmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VmateriasActionPerformed
        VerMateriasFrame menu = new VerMateriasFrame();
        menu.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_VmateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ralumnos;
    private javax.swing.JButton Rmaterias;
    private javax.swing.JButton Rprofes;
    private javax.swing.JButton Valumnos;
    private javax.swing.JButton Vmaterias;
    private javax.swing.JButton Vprofesores;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
