/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar;

import Clases.Alumno;
import Clases.Materia;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class RegistroMateriasFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMateriasFrame
     */
    public RegistroMateriasFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        materiatext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gradotext = new javax.swing.JTextField();
        agregarbutton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        borrarbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("MATERIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        materiatext.setText("Ingresa la Materia");
        getContentPane().add(materiatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("GRADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        gradotext.setText("Ingresa el Grado");
        getContentPane().add(gradotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 30));

        agregarbutton.setBackground(new java.awt.Color(153, 255, 153));
        agregarbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregarbutton.setText("¡AGREGAR!");
        agregarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, 150));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Regresar");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        borrarbutton.setBackground(new java.awt.Color(153, 255, 153));
        borrarbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrarbutton.setText("Borrar todo");
        borrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuaderno.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbuttonActionPerformed
        String _materia = materiatext.getText();
        String _grado = gradotext.getText();
            if(!_materia.equals("") && !_grado.equals("")){
                Materia materia = new Materia(_materia,_grado);
                ControlEscolar.materias[ControlEscolar.tamanomat] = materia;
                ControlEscolar.tamanomat++;
                materiatext.setText("");
                gradotext.setText("");
                System.out.println(ControlEscolar.materias[ControlEscolar.tamanomat-1].getNombre());
                System.out.println(ControlEscolar.materias[ControlEscolar.tamanomat-1].getGrado());
                JOptionPane.showMessageDialog(this, "Agregado con éxito!!");
            }else{
                JOptionPane.showMessageDialog(this, "Rellena todos los datos");
            }
    }//GEN-LAST:event_agregarbuttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void borrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbuttonActionPerformed
        materiatext.setText("");
        gradotext.setText("");
    }//GEN-LAST:event_borrarbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMateriasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMateriasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarbutton;
    private javax.swing.JButton borrarbutton;
    private javax.swing.JTextField gradotext;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField materiatext;
    // End of variables declaration//GEN-END:variables
}
