/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar;

import Clases.Alumno;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class RegistroAlumnosFrame extends javax.swing.JFrame {
    private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    /**
     * Creates new form RegistroAlumnosFrame
     */
    public RegistroAlumnosFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrotext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombretext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        domiciliotext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefonotext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gradotext = new javax.swing.JTextField();
        emailtext = new javax.swing.JTextField();
        calificaciontext = new javax.swing.JTextField();
        borrarbutton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        mujer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        hombre = new javax.swing.JRadioButton();
        agregarbutton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrotext.setText("Ingresa tu Registro");
        getContentPane().add(registrotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("REGISTRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        nombretext.setText("Ingresa tu Nombre");
        getContentPane().add(nombretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE COMPLETO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DOMICILIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        domiciliotext.setText("Ingresa tu Domicilio");
        domiciliotext.setToolTipText("");
        getContentPane().add(domiciliotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("TELEFONO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        telefonotext.setText("Ingresa tu Telefono");
        getContentPane().add(telefonotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("E-MAIL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("GRADO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CALIFICACION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        gradotext.setText("Ingresa tu Grado");
        getContentPane().add(gradotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 190, 30));

        emailtext.setText("Ingresa tu E-mail");
        getContentPane().add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 190, 30));

        calificaciontext.setText("Ingresa tu Calificacion");
        calificaciontext.setToolTipText("");
        getContentPane().add(calificaciontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 190, 30));

        borrarbutton.setBackground(new java.awt.Color(153, 255, 153));
        borrarbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrarbutton.setText("Borrar todo");
        borrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 170, 30));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Regresar");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        mujer.setSelected(true);
        mujer.setText("Mujer");
        mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujerActionPerformed(evt);
            }
        });
        getContentPane().add(mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("SEXO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        hombre.setText("Hombre");
        hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombreActionPerformed(evt);
            }
        });
        getContentPane().add(hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        agregarbutton1.setBackground(new java.awt.Color(153, 255, 153));
        agregarbutton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregarbutton1.setText("¡AGREGAR!");
        agregarbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(agregarbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuaderno.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbuttonActionPerformed
        registrotext.setText("");
        nombretext.setText("");
        domiciliotext.setText("");
        telefonotext.setText("");
        emailtext.setText("");
        gradotext.setText("");
        calificaciontext.setText("");
    }//GEN-LAST:event_borrarbuttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);                          
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hombreActionPerformed
        mujer.setSelected(false);
    }//GEN-LAST:event_hombreActionPerformed

    private void mujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mujerActionPerformed
        hombre.setSelected(false);
    }//GEN-LAST:event_mujerActionPerformed

    private void agregarbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbutton1ActionPerformed
        String registro = registrotext.getText();
        String nombre = nombretext.getText();
        String domicilio  = domiciliotext.getText();
        String telefono = telefonotext.getText();
        String email = emailtext.getText();
        String grado = gradotext.getText();
        String calificacion = calificaciontext.getText();
        boolean verdadero = false;
        System.out.println("El tamaño de calificacion es de: " + calificacion.length());
        if (RegistroAlumnosFrame.isNumeric(calificacion)){
            verdadero = true;
        }
        if(verdadero){
            if(!registro.equals("") && !nombre.equals("") && !domicilio.equals("") && !telefono.equals("") && !email.equals("") && !grado.equals("")){
                int newcalif = Integer.parseInt(calificaciontext.getText());
                boolean sexo = false;
                if(hombre.isSelected()){
                    sexo = true;
                }
                else if(mujer.isSelected()){
                    sexo = false;
                }
                Alumno alumno = new Alumno(registro,nombre,domicilio,telefono,email,grado,sexo,newcalif);
                ControlEscolar.alumnos[ControlEscolar.tamanoalumn] = alumno;
                ControlEscolar.tamanoalumn++;
                registrotext.setText("");
                nombretext.setText("");
                domiciliotext.setText("");
                telefonotext.setText("");
                emailtext.setText("");
                gradotext.setText("");
                calificaciontext.setText("");
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getRegistro());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getNombre());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getDomicilio());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getTelefono());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getEmail());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getCalificacion());
                System.out.println(ControlEscolar.alumnos[ControlEscolar.tamanoalumn-1].getGrado());
                JOptionPane.showMessageDialog(this, "Agregado con éxito!!");
            }else{
                JOptionPane.showMessageDialog(this, "Rellena todos los datos");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tu calificacion no se supone que sea un string, ingresa un entero");
            calificaciontext.setText("");
        }
    }//GEN-LAST:event_agregarbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlumnosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarbutton1;
    private javax.swing.JButton borrarbutton;
    private javax.swing.JTextField calificaciontext;
    private javax.swing.JTextField domiciliotext;
    private javax.swing.JTextField emailtext;
    private javax.swing.JTextField gradotext;
    private javax.swing.JRadioButton hombre;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mujer;
    private javax.swing.JTextField nombretext;
    private javax.swing.JTextField registrotext;
    private javax.swing.JTextField telefonotext;
    // End of variables declaration//GEN-END:variables
}
