/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlescolar;

import javax.swing.DefaultListModel;

/**
 *
 * @author carlo
 */
public class VerProfesoresFrame extends javax.swing.JFrame {

    /**
     * Creates new form VerProfesoresFrame
     */
    public VerProfesoresFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        carga = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        registrotext = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombretext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        domiciliotext = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telefonotext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sexotext = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gradoacademicotext = new javax.swing.JLabel();
        borrarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 220, 340));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Regresar");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        carga.setBackground(new java.awt.Color(204, 255, 204));
        carga.setText("Cargar Profesores");
        carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaActionPerformed(evt);
            }
        });
        getContentPane().add(carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 140, 30));

        jLabel1.setText("Registro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 90, 20));

        registrotext.setText("-");
        getContentPane().add(registrotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 150, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        nombretext.setText("-");
        getContentPane().add(nombretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 150, -1));

        jLabel3.setText("Domicilio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        domiciliotext.setText("-");
        getContentPane().add(domiciliotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, -1));

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        telefonotext.setText("-");
        getContentPane().add(telefonotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 150, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        emailtext.setText("-");
        getContentPane().add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 150, -1));

        jLabel8.setText("Sexo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        sexotext.setText("-");
        getContentPane().add(sexotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));

        jLabel9.setText("Grado Academico");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        gradoacademicotext.setText("-");
        getContentPane().add(gradoacademicotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 150, -1));

        borrarbutton.setBackground(new java.awt.Color(255, 0, 0));
        borrarbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrarbutton.setText("Borrar todo");
        borrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaActionPerformed
        DefaultListModel dim = new DefaultListModel<>();
        for ( int i = 0; i < ControlEscolar.tamanoprof; i++ ){
            dim.addElement(ControlEscolar.profesores[i].getNombre());
        }
        jList1.setModel(dim);
    }//GEN-LAST:event_cargaActionPerformed

    private void borrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbuttonActionPerformed
        registrotext.setText("-");
        nombretext.setText("-");
        domiciliotext.setText("-");
        telefonotext.setText("-");
        emailtext.setText("-");
        gradoacademicotext.setText("-");
        sexotext.setText("-");
    }//GEN-LAST:event_borrarbuttonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int selected = jList1.getSelectedIndex();
        registrotext.setText(ControlEscolar.profesores[selected].getRegistro());
        nombretext.setText(ControlEscolar.profesores[selected].getNombre());
        domiciliotext.setText(ControlEscolar.profesores[selected].getDomicilio());
        telefonotext.setText(ControlEscolar.profesores[selected].getTelefono());
        emailtext.setText(ControlEscolar.profesores[selected].getEmail());
        boolean sex  = ControlEscolar.profesores[selected].isSexo();
        int gradoacademico = ControlEscolar.profesores[selected].getGradoestudio();
        if(sex){
            sexotext.setText("Hombre");
        }else{
            sexotext.setText("Mujer");
        }
        switch(gradoacademico){
            case 1:
                gradoacademicotext.setText("Licenciatura");
                break;
            case 2:
                gradoacademicotext.setText("Maestría");
                break;
            case 3:
                gradoacademicotext.setText("Doctorado");
                break;
        }
    }//GEN-LAST:event_jList1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProfesoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProfesoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProfesoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProfesoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProfesoresFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarbutton;
    private javax.swing.JToggleButton carga;
    private javax.swing.JLabel domiciliotext;
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel gradoacademicotext;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombretext;
    private javax.swing.JLabel registrotext;
    private javax.swing.JLabel sexotext;
    private javax.swing.JLabel telefonotext;
    // End of variables declaration//GEN-END:variables
}
