CREATE CERTIFICATE cifrado01
WITH SUBJECT='cifrado'
go

select * from sys.certificates;
go


CREATE SYMMETRIC KEY NIP_KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE cifrado01;
go

ALTER TABLE dbo.Usuario
ADD NIP_ENCRYPTED varbinary(800);

ALTER TABLE dbo.Usuario
ALTER COLUMN NIP VARCHAR(10);

OPEN SYMMETRIC KEY NIP_KEY
DECRYPTION BY CERTIFICATE cifrado01;


UPDATE Usuario
SET NIP_ENCRYPTED = ENCRYPTBYKEY(KEY_GUID('NIP_KEY'),CONVERT(VARBINARY,NIP))

SELECT * FROM Usuario;

CLOSE SYMMETRIC KEY NIP_KEY;

OPEN SYMMETRIC KEY NIP_KEY
DECRYPTION BY CERTIFICATE cifrado01;

select CONVERT(varchar(10),DECRYPTBYKEY(NIP_ENCRYPTED)) as [NIP desifrado], NIP FROM Usuario;
CLOSE SYMMETRIC KEY NIP_KEY;



